org.gradle.daemon=false
org.gradle.jvmargs=-Xmx4G

# JER
modName=Just Enough Resources
modFileName=JustEnoughResources
modId=jeresources
modAuthor=way2muchnoise
modGroup=jeresources
# Mojang ships Java 25 to end users in 26.1+
modJavaVersion=25
githubUrl=github.com/way2muchnoise/JustEnoughResources

# Architecutury
platforms=fabric,forge,neoforge

# Minecraft
minecraftVersion=26.2
minecraftVersionRange=[26.2, 26.3)

# Forge
forgeVersion=65.0.9
loaderVersionRange=[64,)
forgeVersionRange=[64.0.0,)

# Fabric
fabricVersion=0.155.2+26.2
fabricLoaderVersion=0.19.3

# NeoForge
neoforgeVersion=26.2.0.28-beta
neoforgeLoaderVersionRange=[4,)
neoforgeVersionRange=[26.2.0,)

#JEI
jeiVersion=30.13.0.79

# Fabric Config screen
clothVersion=26.2.155
modMenuVersion=20.0.1

# Mappings
mappingsChannel=parchment
mappingsParchmentMinecraftVersion=1.21.11
mappingsParchmentVersion=2025.12.20

# Publishing
curseProjectId=240630
curseHomepageLink=https://www.curseforge.com/minecraft/mc-mods/just-enough-resources-jer
modrinthProjectId=uEfK2CXF

# Version
specificationVersion=1.10.0
