org.gradle.daemon=false
org.gradle.jvmargs=-Xmx4G

# JER
modName=Just Enough Resources
modFileName=JustEnoughResources
modId=jeresources
modAuthor=way2muchnoise
modGroup=jeresources
# Mojang ships Java 25 to end users in 26.1+
modJavaVersion=25
githubUrl=github.com/way2muchnoise/JustEnoughResources

# Architecutury
platforms=fabric,neoforge

# Minecraft
minecraftVersion=26.3
minecraftVersionRange=[26.3, 26.4)

# Fabric
fabricVersion=0.161.0+26.3
fabricLoaderVersion=0.19.5

# NeoForge
neoforgeVersion=26.3.0.31-beta
neoforgeLoaderVersionRange=[4,)
neoforgeVersionRange=[26.3.0,)

#JEI
jeiVersion=31.7.0.47

# Fabric Config screen
clothVersion=26.3.158
modMenuVersion=21.0.0

# Publishing
curseProjectId=240630
curseHomepageLink=https://www.curseforge.com/minecraft/mc-mods/just-enough-resources-jer
modrinthProjectId=uEfK2CXF

# Version
specificationVersion=1.11.0
