package jeresources.reference;

import net.minecraftforge.fml.common.ModMetadata;

import java.util.Collections;

public class MetaData
{
    /**
     * Setup mod metadata
     *
     * @param metadata
     * @return edited metadata object
     */
    public static ModMetadata init(ModMetadata metadata)
    {
        metadata.modId = Reference.ID;
        metadata.name = Reference.NAME;
        metadata.description = Reference.NAME + " is an addon for JEI that adds tons of stuff about world gen, plant drop, mob loot, chest loot, villagers and enchantments";
        //metadata.url = "";
        //metadata.logoFile = "assets/" + Reference.ID + "/logo.png";
        metadata.version = Reference.VERSION;
        metadata.authorList = Collections.singletonList("way2muchnoise");
        //metadata.credits = "";
        metadata.autogenerated = false;
        return metadata;
    }
}
